/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.peluqueria.canina.igu;

import com.mycompany.peluqueria.canina.logica.Controladora;
import com.mycompany.peluqueria.canina.logica.Mascota;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
/**
 *
 * @author Joaquin
 */
public class EditarMascota extends javax.swing.JFrame {
    
    Controladora controladora = null;
   private int id_mascota;
   private Mascota mascota;

    /**
     * Creates new form CargaDeDatos
     */
    public EditarMascota(int id_mascota) {
        initComponents();
        controladora = new Controladora();
        this.id_mascota = id_mascota;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        razaTextField = new javax.swing.JTextField();
        celDuenioTextField = new javax.swing.JTextField();
        colorTextField = new javax.swing.JTextField();
        nameDuenioTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        obervationsTextArea = new javax.swing.JTextArea();
        isAlergico = new javax.swing.JComboBox<>();
        hasSpecialAtention = new javax.swing.JComboBox<>();
        cleanBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        dirDuenioTextField = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("MODIFICAR MASCOTA");

        jLabel2.setText("Nombre Animalito");

        jLabel3.setText("Raza");

        jLabel4.setText("Color");

        jLabel5.setText("Alergico");

        jLabel6.setText("Atencion especial");

        jLabel7.setText("Nombre duenio");

        jLabel8.setText("Observaciones");

        jLabel9.setText("Cel duenio");

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        razaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                razaTextFieldActionPerformed(evt);
            }
        });

        celDuenioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celDuenioTextFieldActionPerformed(evt);
            }
        });

        colorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorTextFieldActionPerformed(evt);
            }
        });

        nameDuenioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameDuenioTextFieldActionPerformed(evt);
            }
        });

        obervationsTextArea.setColumns(20);
        obervationsTextArea.setRows(5);
        jScrollPane1.setViewportView(obervationsTextArea);

        isAlergico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Si", "No" }));
        isAlergico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isAlergicoActionPerformed(evt);
            }
        });

        hasSpecialAtention.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Si", "No" }));
        hasSpecialAtention.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasSpecialAtentionActionPerformed(evt);
            }
        });

        cleanBtn.setText("Limpiar");
        cleanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanBtnActionPerformed(evt);
            }
        });

        saveBtn.setText("Guardar Cambios");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        jLabel10.setText("Direccion duenio");

        dirDuenioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dirDuenioTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(cleanBtn))
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)))
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(celDuenioTextField)
                                .addComponent(razaTextField)
                                .addComponent(nameTextField)
                                .addComponent(colorTextField)
                                .addComponent(nameDuenioTextField)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                .addComponent(dirDuenioTextField))
                            .addComponent(isAlergico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hasSpecialAtention, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(saveBtn)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(razaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(colorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(isAlergico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(hasSpecialAtention, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(nameDuenioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(celDuenioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(dirDuenioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cleanBtn)
                    .addComponent(saveBtn))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void razaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_razaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_razaTextFieldActionPerformed

    private void celDuenioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celDuenioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celDuenioTextFieldActionPerformed

    private void colorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorTextFieldActionPerformed

    private void nameDuenioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameDuenioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameDuenioTextFieldActionPerformed

    private void isAlergicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isAlergicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isAlergicoActionPerformed

    private void hasSpecialAtentionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasSpecialAtentionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasSpecialAtentionActionPerformed

    private void cleanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanBtnActionPerformed
        // TODO add your handling code here:
        celDuenioTextField.setText("");
        colorTextField.setText("");
        nameDuenioTextField.setText("");
        nameTextField.setText("");
        obervationsTextArea.setText("");
        razaTextField.setText("");
        dirDuenioTextField.setText("");
        
        
        isAlergico.setSelectedIndex(0);
        hasSpecialAtention.setSelectedIndex(0);
        
        
    }//GEN-LAST:event_cleanBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        
         //aca vamos a obtener todos los datos del formulario y pasarselos 
         //a la funcion de la controladora para que se encarge de guardarlos
         //sea donde sea, 
         //pero desde aca, solo pasamos los datos, de la logica se encarga
         //la otra funcion...
         
         
         //DUENO
         String duenoName = nameDuenioTextField.getText();
         String duenoPhone = celDuenioTextField.getText();
         String duenoAddress = dirDuenioTextField.getText();
         
         //MASCOTA
         String petName = nameTextField.getText();
         String petColor = colorTextField.getText();
         String petRaza = razaTextField.getText();
         String observations = obervationsTextArea.getText();
         

         String preIsAlergico = (String) isAlergico.getSelectedItem(); 
         String preHasAtention = (String) hasSpecialAtention.getSelectedItem();
         boolean petIsAlergico = preIsAlergico.contentEquals("Si") ? true : false;
         boolean petHasSpecialAtention = preHasAtention.contentEquals("Si") ? true : false;
    
         //controladora.guardarMascota(duenoName, duenoPhone, duenoAddress, petName, petColor, petRaza, observations, petIsAlergico, petHasSpecialAtention);
         /*
         Es importante pasarle el objeto viejo de mascota, el que recuperamos antes, ya que
         tenemos la misma posicion en memoria del objeto original, es por eso
         que JPA va a poder modificar el objeto REAL.
         Ademas de ese objeto obtenemos el ID del dueno para editar
*/
         controladora.editarMascota(
                 this.mascota,
                 petName, 
                 petColor,
                 petRaza,
                 observations,
                 petIsAlergico,
                 petHasSpecialAtention,
                 duenoName,
                 duenoPhone,
                 duenoAddress
               
        );
        
         
         JOptionPane jOptionPane = new JOptionPane("Se edito correctamente");
         jOptionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
         JDialog dialog = jOptionPane.createDialog("Editar Mascota");
         dialog.setAlwaysOnTop(true);
         dialog.setVisible(true);
         
         this.cleanBtnActionPerformed(evt);

    }//GEN-LAST:event_saveBtnActionPerformed

    private void dirDuenioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirDuenioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dirDuenioTextFieldActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        inicializarPantalla();
        
    }//GEN-LAST:event_formWindowOpened
    
    private void inicializarPantalla(){
          this.mascota = controladora.obtenerMascota(this.id_mascota);
         
         celDuenioTextField.setText(mascota.getDueno().getPhone());
        colorTextField.setText(mascota.getColor());
        nameDuenioTextField.setText(mascota.getDueno().getDuenoName());
        nameTextField.setText(mascota.getNombre_mascota());
        obervationsTextArea.setText(mascota.getObservations());
        razaTextField.setText(mascota.getRaza());
        dirDuenioTextField.setText(mascota.getDueno().getAddress());
        
        
        isAlergico.setSelectedIndex(mascota.isIsAlergico() ? 1 : 2);
        hasSpecialAtention.setSelectedIndex(mascota.isHasSpecialAtention() ? 1 : 2);

    }
     
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField celDuenioTextField;
    private javax.swing.JButton cleanBtn;
    private javax.swing.JTextField colorTextField;
    private javax.swing.JTextField dirDuenioTextField;
    private javax.swing.JComboBox<String> hasSpecialAtention;
    private javax.swing.JComboBox<String> isAlergico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField nameDuenioTextField;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextArea obervationsTextArea;
    private javax.swing.JTextField razaTextField;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
